### ISSUE TITLE
[bug] No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by Kavinraja-G** [portworx/pxc#198]
**Describe the bug**
When I try to use pxctl kubeclt plugin with OIDC authenticated clusters, I'm facing the below errors --
```
❯ kubectl-pxc config cluster set --portworx-service-namespace=portworx
Cluster information set

❯ pxctl status
unable to connect to Kubernetes: no Auth Provider found for name "oidc"
Unable to find node that is online
```

[Kubernetes](https://github.com/kubernetes/client-go/issues/345) suggests to import `k8s.io/client-go/plugin/pkg/client/auth/oidc` for OIDC based clusters for authentication.

**Version**

**Additional Information**

**Comment by lpabon** [comment]
Thank you for PR #199. I used that as the basis of #200 and took the opportunity to update a lot of the go-mods.

Please try one of the builds below and let me know how it goes.

[pxc-v0.35.0-5-g885b872-issue198.windows.amd64.zip](https://github.com/portworx/pxc/files/13056473/pxc-v0.35.0-5-g885b872-issue198.windows.amd64.zip)
[pxc-v0.35.0-5-g885b872-issue198.linux.amd64.tar.gz](https://github.com/portworx/pxc/files/13056475/pxc-v0.35.0-5-g885b872-issue198.linux.amd64.tar.gz)
[pxc-v0.35.0-5-g885b872-issue198.darwin.arm64.tar.gz](https://github.com/portworx/pxc/files/13056479/pxc-v0.35.0-5-g885b872-issue198.darwin.arm64.tar.gz)
[pxc-v0.35.0-5-g885b872-issue198.darwin.amd64.tar.gz](https://github.com/portworx/pxc/files/13056480/pxc-v0.35.0-5-g885b872-issue198.darwin.amd64.tar.gz)
